project:
  type: website

website:
  title: "R-Ladies Melbourne Inc"
  favicon: images/favicon.png
  google-analytics: "G-CB5M3V95HB"
  cookie-consent: true
  navbar: 
    background: "#88398A"
    search: true 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: blog_index.qmd
        text: Blog
      - href: https://github.com/R-LadiesMelbourne/Links-to-Events-Repos
        text: Links to Events Repos
      - text: Our Work
        menu:
          - href: ourwork.qmd 
            text: Overview 
          - href: outputs/redu_itas.qmd
            text: It Takes a Spark
          - href: outputs/eoy2024.qmd
            text: 2024 End of Year Event
      - href: timeline.qmd
        text: Our Legacy
      - href: resources.qmd
        text: Resources
    tools:
      - icon: twitter-x
        href: https://twitter.com/RLadiesMelb
      - icon: fab fa-meetup
        href: https://www.meetup.com/rladies-melbourne/
      - icon: youtube
        href: https://www.youtube.com/channel/UClC5yNEjMoE3MmbK-mrV8Ow 
      - icon: envelope-fill
        href: rladiesmelbourne@gmail.com
      - icon: slack
        href: https://join.slack.com/t/r-ladiesmelbourne/shared_invite/zt-2l871qpk6-4EbxzUm2M5ow8vpXDZMspg 
      - icon: github
        href: https://github.com/R-LadiesMelbourne
        menu:
          - text: Source Code
            href: https://github.com/R-LadiesMelbourne/r-ladiesmelbourne.github.io
          - text: Report a Bug
            href: https://github.com/R-LadiesMelbourne/r-ladiesmelbourne.github.io/issues
  #repo-url: https://github.com/quarto-dev/quarto-demo follow this tutorial here: https://quarto.org/docs/websites/website-navigation.html#github-links
  #repo-actions: [edit, source, issue]
  page-footer: 
    left: "Copyright 2024, R-Ladies Melbourne"
    right: 
      - icon: twitter-x
        href: https://twitter.com/RLadiesMelb
      - icon: fab fa-meetup
        href: https://www.meetup.com/rladies-melbourne/
      - icon: youtube
        href: https://www.youtube.com/channel/UClC5yNEjMoE3MmbK-mrV8Ow 
      - icon: envelope-fill
        href: rladiesmelbourne@gmail.com
      - icon: slack
        href: https://join.slack.com/t/r-ladiesmelbourne/shared_invite/zt-2l871qpk6-4EbxzUm2M5ow8vpXDZMspg 
      - icon: github
        href: https://github.com/R-LadiesMelbourne

    
format:
  html:
    theme:
      light: [cosmo, quarto-ext/bootstrap]
      dark: [cosmo, styles/theme-dark.css]
    css: 
      - styles/styles.css
      - styles/all.min.css
    toc: true
    fontawesome: true

editor: visual
