---
title: "Meetup: 14 Aug 2025: R-Ladies Social Night"
author: "Felicia Bongiovanni"
date: "2025-08-14"
categories: [Event, Social]
---

## Introducing our Social Nights! 

Come unwind and connect with like-minded people at our first R-Ladies Social Night! Whether you’ve been to one of our events in the past or you’re just starting out, this evening will be about building community and getting to know each other better.

::: column-margin
Sign up on the R-Ladies Melbourne [**meetup page**](https://www.meetup.com/rladies-melbourne/events/310287919/).

Time: Thu, Aug 14, 2025

5:30 PM to 7:30 PM AEST

Location: Father's Office (249 Lt Lonsdale St, Melbourne)
:::

Meet us at Father’s Office on August 14 for a casual meet up with good vibes and great company. Make sure to come on time to take advantage of the Father’s Office happy hour!

We look forward to seeing you there.

*Please note that food and drinks are not provided at this event and are at the attendee’s expense.

💜 Felicia on behalf of R-Ladies Melbourne

[Back to our blog home page](../blog_index.qmd)